package com.myjob.jobseeker.model;

import java.util.Date;

import org.springframework.data.mongodb.core.mapping.Document;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "password_reset_tokens")
public class PasswordResetToken {

    private int id;              // Unique identifier for the token (automatically generated by MongoDB)
    private String token;           // The actual token string
    private int userId;          // Reference to the user who requested the password reset
    private Date expiryDate;        // Expiration date for the token


    @Override
    public String toString() {
        return "PasswordResetToken{" +
                "id='" + id + '\'' +
                ", token='" + token + '\'' +
                ", userId='" + userId + '\'' +
                ", expiryDate=" + expiryDate +
                '}';
    }
}
